export const ON_CLICK_HAMBURGER_MENU = 'ON_CLICK_HAMBURGER_MENU';
export const ON_CLICK_MENU_CLOSE = 'ON_CLICK_HAMBURGER_MENU_CLOSE';
export const PUT_DATA = 'PUT_DATA';
export const LOAD_DATA = 'LOAD_DATA';